baseURL = "https://m.gean.me/"
languageCode = "pt-br"
title = "The Memories"
theme = "ink"
paginate = 5

copyright = "The Memories"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-23205651-1"
disqusShortname = "geanramos"

[params]
	subtitle = "histórias que emocionam."

	# Optional 64x64 avatar image.
	avatar = "https://i0.wp.com/imageup.me/images/panda.jpeg?resize=80,80"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "dark" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Sobre"
url = "/sobre"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "Telegram"
url = "https://t.me/+1CfO3FKK6ts4Y2Ex"
weight = 4

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter/geanramos"

[[params.social]]
name = "Telegram"
icon = "coffee"
url = "https://nubank.com.br/pagar/13s98d/RqJRPjJZJB"

[taxonomies]
   tag = "tags"
