baseURL = "https://memories.geanramos.com/"
languageCode = "pt-br"
title = "The Memories"
theme = "ink"
paginate = 5

copyright = "© Copyright"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-23205651-1"
disqusShortname = "geanramos"

[params]
	subtitle = "histórias que emociona.♥️)"

	# Optional 64x64 avatar image.
	avatar = "https://img.freepik.com/free-vector/cute-unicorn-reading-book-cartoon-vector-illustration-animal-education-concept-isolated-vector-flat-cartoon-style_138676-1945.jpg?w=128"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "dark" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Memories"
url = "/posts"
weight = 2

[[menu.main]]
name = "Sobre"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://instagr.am/geanramus"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
