baseURL = "https://memories.geanramos.com/"
languageCode = "pt-br"
title = "The Memories"
theme = "ink"
paginate = 5

copyright = "© Copyright"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-23205651-1"
disqusShortname = "geanramos"

[params]
	subtitle = "histórias que emocionam💖"

	# Optional 64x64 avatar image.
	avatar = "https://pbs.twimg.com/profile_images/833573742353711107/T45OvTDl_400x400.jpg"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "dark" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Sobre"
url = "/about"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "Pague-me um ☕"
url = "https://nubank.com.br/pagar/13s98d/RqJRPjJZJB"
weight = 4

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter/geanramos"

[taxonomies]
   tag = "tags"
